// Copyright 2020-2021 Beken
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


#include "stdint.h"
#include "stdbool.h"
#include "drv_model_pub.h"
#include <driver/uart.h>
#include "bk_uart.h"
#include <components/log.h>
#include "sys_config_check.h"

#define TAG    "config"
bool bk_config_check(void)
{
	CONFIG_SDIO_CREDITS_CHECK();
	CONFIG_CAMERA_CHECK();
	CONFIG_SPI_MASTER_CHECK();
	CONFIG_BEACON_VENDOR_API_CHECK();
	DD_DEV_TYPE_SARADC_CHECK();
	CONFIG_BLE_PS_CHECK();
	DD_DEV_TYPE_UART2_CHECK();
	CONFIG_WPA3_ENTERPRISE_CHECK();
	CONFIG_TEMP_DETECT_CHECK();
	CONFIG_MAC_PHY_BYPASS_CHECK();
	DD_DEV_TYPE_AUD_DAC_CHECK();
	CONFIG_SOC_BK7236_CHECK();
	CONFIG_WIFI6_IP_DEBUG_CHECK();
	DD_DEV_TYPE_DSP_CHECK();
	CONFIG_WIFI_P2P_GO_CHECK();
	CONFIG_BLE_MESH_RW_CHECK();
	DD_DEV_TYPE_MPB_CHECK();
	CONFIG_DHCP_CHECK();
	CONFIG_CALI_CHECK();
	DD_DEV_TYPE_SCTRL_CHECK();
	CONFIG_RF_OTA_TEST_CHECK();
	CONFIG_BACKGROUND_PRINT_CHECK();
	CONFIG_TASK_USB_PRIO_CHECK();
	CONFIG_UART_DEBUG_CHECK();
	CONFIG_FPGA_CHECK();
	CONFIG_RF_POLICY_BLE_REQ_CHECK();
	CONFIG_HSLAVE_SPI_CHECK();
	CONFIG_USB_HOST_CHECK();
	CONFIG_MSDU_RESV_HEAD_LEN_CHECK();
	DD_DEV_TYPE_SDIO_CHECK();
	CONFIG_INT_WDT_PERIOD_MS_CHECK();
	CONFIG_MALLOC_STATIS_CHECK();
	CONFIG_BT_SRC_ADD_CHECK();
	CONFIG_UART3_CHECK();
	CONFIG_WIFI_RAW_TX_TEST_CHECK();
	DD_DEV_TYPE_IRDA_CHECK();
	CONFIG_PERI_TEST_CHECK();
	CONFIG_WPA_CTRL_IFACE_CHECK();
	DD_DEV_TYPE_USB_PLUG_CHECK();
	CONFIG_FAKE_RTC_PS_CHECK();
	CONFIG_RWNX_QOS_MSDU_CHECK();
	CONFIG_SPI_SLAVE_CHECK();
	CONFIG_SOC_BK7271_CHECK();
	CONFIG_FFT_CHECK();
	CONFIG_USB_UVC_CHECK();
	CONFIG_NO_HOSTED_CHECK();
	CONFIG_UART_TEST_CHECK();
	CONFIG_MP3PLAYER_CHECK();
	DD_DEV_TYPE_UART3_CHECK();
	CONFIG_BSSID_CONNECT_CHECK();
	CONFIG_BT_MESH_CFG_CLI_CHECK();
	CONFIG_WPA_LOG_CHECK();
	CONFIG_LWIP_CHECK();
	CONFIG_MANUAL_CALI_CHECK();
	CONFIG_TASK_WPAS_PRIO_CHECK();
	CONFIG_WIFI6_CODE_STACK_CHECK();
	CONFIG_SDCARD_HOST_CHECK();
	CONFIG_SOC_BK7231N_CHECK();
	CONFIG_USB_DEVICE_CHECK();
	CONFIG_UDISK_MP3_CHECK();
	CONFIG_USE_CONV_UTF8_CHECK();
	CONFIG_BT_CHECK();
	CONFIG_RF_POLICY_WIFI_REQ_CHECK();
	DD_DEV_TYPE_FFT_CHECK();
	CONFIG_TASK_WDT_CHECK();
	CONFIG_UART1_CHECK();
	CONFIG_CUSTOMER_DRONE_CHECK();
	CONFIG_I2S_CHECK();
	CONFIG_BT_MESH_ADV_LEGACY_CHECK();
	CONFIG_TASK_WDT_PERIOD_MS_CHECK();
	CONFIG_SPI_MST_FLASH_CHECK();
	DD_DEV_TYPE_ICU_CHECK();
	CONFIG_AP_HE_CHECK();
	CONFIG_WIFI6_CHECK();
	CONFIG_LWIP_MEM_REDUCE_CHECK();
	CONFIG_WIFI_KMSG_TASK_STACK_SIZE_CHECK();
	CONFIG_USB_CHECK();
	CONFIG_PMF_CHECK();
	CONFIG_TICK_CALI_CHECK();
	DD_DEV_TYPE_MAILBOX_CHECK();
	CONFIG_USB1_PORT_CHECK();
	CONFIG_SPI_TEST_CHECK();
	CONFIG_BLE_HOST_RW_CHECK();
	CONFIG_WIFI_CORE_TASK_STACK_SIZE_CHECK();
	CONFIG_BLE_CONN_NUM_CHECK();
	CONFIG_UART2_CHECK();
	CONFIG_WFA_CERT_CHECK();
	CONFIG_BLE_5_X_CHECK();
	CONFIG_TRNG_SUPPORT_CHECK();
	CONFIG_WPA_SME_CHECK();
	CONFIG_AT_CHECK();
	CONFIG_MEM_DEBUG_CHECK();
	CONFIG_BLE_MESH_ZEPHYR_CHECK();
	CONFIG_USB_CCD_CHECK();
	CONFIG_AP_IDLE_CHECK();
	CONFIG_WIFI_SENSOR_CHECK();
	CONFIG_INT_WDT_CHECK();
	CONFIG_BEACON_UPDATE_API_CHECK();
	DD_DEV_TYPE_TIMER_CHECK();
	DD_DEV_TYPE_EJPEG_CHECK();
	CONFIG_WIFI_KMSG_TASK_PRIO_CHECK();
	CONFIG_WIFI_CORE_TASK_PRIO_CHECK();
	DD_DEV_TYPE_UART1_CHECK();
	CONFIG_WPA2_ENTERPRISE_CHECK();
	CONFIG_GENERAL_DMA_CHECK();
	CONFIG_SECURITY_CHECK();
	DD_DEV_TYPE_QSPI_CHECK();
	CONFIG_SEMI_HOSTED_CHECK();
	DD_DEV_TYPE_USB_CHECK();
	CONFIG_TPC_PA_MAP_CHECK();
	CONFIG_IPERF_TEST_CHECK();
	CONFIG_FULLY_HOSTED_CHECK();
	CONFIG_SOC_BK7231U_CHECK();
	CONFIG_STA_PS_CHECK();
	CONFIG_SPI_DMA_CHECK();
	DD_DEV_TYPE_RF_CHECK();
	CONFIG_AP_MONITOR_COEXIST_CHECK();
	CONFIG_AP_HT_IE_CHECK();
	CONFIG_PTA_CHECK();
	CONFIG_BASE_MAC_FROM_NVS_CHECK();
	CONFIG_WFA_CA_CHECK();
	CONFIG_WIFI_P2P_CHECK();
	CONFIG_DEEP_PS_CHECK();
	DD_DEV_TYPE_I2S_CHECK();
	CONFIG_XTAL_FREQ_40M_CHECK();
	CONFIG_DEBUG_FIRMWARE_CHECK();
	CONFIG_LWIP_2_1_2_CHECK();
	CONFIG_USB_HID_CHECK();
	DD_DEV_TYPE_END_CHECK();
	CONFIG_USB_MSD_CHECK();
	DD_DEV_TYPE_SPIDMA_CHECK();
	DD_DEV_TYPE_FLASH_CHECK();
	CONFIG_WPA3_CHECK();
	CONFIG_XTAL_FREQ_26M_CHECK();
	CONFIG_BLE_SCAN_NUM_CHECK();
	CONFIG_XTAL_FREQ_CHECK();
	CONFIG_DCACHE_CHECK();
	DD_DEV_TYPE_BLE_CHECK();
	CONFIG_DSP_SRC_ADD_CHECK();
	DD_DEV_TYPE_GDMA_CHECK();
	CONFIG_OTA_TFTP_CHECK();
	CONFIG_MSDU_RESV_TAIL_LEN_CHECK();
	CONFIG_BK_ASSERT_REBOOT_CHECK();
	CONFIG_SPI_MST_PSRAM_CHECK();
	DD_DEV_TYPE_PWM_CHECK();
	CONFIG_BKREG_CHECK();
	DD_DEV_TYPE_BT_CHECK();
	DD_DEV_TYPE_TRNG_CHECK();
	CONFIG_DEMO_TEST_CHECK();
	CONFIG_TASK_LWIP_PRIO_CHECK();
	CONFIG_I2C2_TEST_CHECK();
	CONFIG_RF_POLICY_CO_REQ_CHECK();
	CONFIG_AIRKISS_TEST_CHECK();
	DD_DEV_TYPE_SPI_CHECK();
	CONFIG_AP_VHT_CHECK();
	DD_DEV_TYPE_SPI2_CHECK();
	CONFIG_FTPD_UPGRADE_CHECK();
	DD_DEV_TYPE_CAL_CHECK();
	CONFIG_BT_MESH_HEALTH_CLI_CHECK();
	CONFIG_DSP_CHECK();
	CONFIG_SDIO_CHECK();
	CONFIG_MCU_PS_CHECK();
	CONFIG_WIFI_FAST_CONNECT_CHECK();
	DD_DEV_TYPE_START_CHECK();
	CONFIG_TCP_SERVER_TEST_CHECK();
	CONFIG_SYS_REDUCE_NORMAL_POWER_CHECK();
	CONFIG_QSPI_CHECK();
	DD_DEV_TYPE_SDCARD_CHECK();
	DD_DEV_TYPE_NONE_CHECK();
	CONFIG_SDIO_TRANS_CHECK();
	DD_DEV_TYPE_GPIO_CHECK();
	CONFIG_RX_SENSE_TEST_CHECK();
	CONFIG_BLE_ADV_NUM_CHECK();
	CONFIG_LWIP_MEM_DEFAULT_CHECK();
	CONFIG_POWER_TABLE_CHECK();
	DD_DEV_TYPE_WDT_CHECK();
	DD_DEV_TYPE_I2C1_CHECK();
	CONFIG_BK_ASSERT_HALT_CHECK();
	CONFIG_SARADC_CALI_CHECK();
	CONFIG_TASK_RECONNECT_PRIO_CHECK();
	CONFIG_WIFI_SCAN_CH_TIME_CHECK();
	CONFIG_I2C1_TEST_CHECK();
	CONFIG_FREERTOS_V10_CHECK();
	CONFIG_JTAG_CHECK();
	DD_DEV_TYPE_SPI3_CHECK();
	CONFIG_BASE_MAC_FROM_EFUSE_CHECK();
	CONFIG_REAL_SDIO_CHECK();
	CONFIG_SDIO_BLOCK_512_CHECK();
	CONFIG_BLE_HOST_ZEPHYR_CHECK();
	CONFIG_SOC_BK7251_CHECK();
	CONFIG_WIFI4_CHECK();
	CONFIG_SOC_BK7231_CHECK();
	CONFIG_USB_CHARGE_CHECK();
	CONFIG_AP_PS_CHECK();
	CONFIG_LESS_MEMERY_IN_RWNX_CHECK();
	CONFIG_UART_DMA_CHECK();
	CONFIG_BK7221_MDM_WATCHDOG_PATCH_CHECK();
	CONFIG_SPIDMA_CHECK();
	CONFIG_BLE_4_2_CHECK();
	CONFIG_BLE_INIT_NUM_CHECK();
	CONFIG_SUPPORT_IRDA_CHECK();
	CONFIG_APP_DEMO_VIDEO_TRANSFER_CHECK();
	CONFIG_TX_EVM_TEST_CHECK();
	CONFIG_AP_PROBEREQ_CB_CHECK();
	CONFIG_PCM_RESAMPLER_CHECK();
	CONFIG_BUTTON_CHECK();
	DD_DEV_TYPE_I2C2_CHECK();
	CONFIG_BLE_CHECK();
	CONFIG_WIFI_WPS_CHECK();
	return true;
}