#ifndef _ICU_BK7271_H_
#define _ICU_BK7271_H_

#define ICU_BASE                                     (0x00802000)

#define ICU_PERI_CLK_MUX                             (ICU_BASE + 0 * 4)
#define PERI_CLK_26M_XTAL                            (1)
#define PERI_CLK_DCO                                 (0)
#define PERI_CLK_UART1                               (1 << 0)
#define PERI_CLK_UART2                               (1 << 1)
#define PERI_CLK_UART3                               (1 << 2)
#define PERI_CLK_IRDA                                (1 << 3)
#define PERI_CLK_FM_I2C                              (1 << 4)
#define PERI_CLK_I2C1                                (1 << 5)
#define PERI_CLK_I2C2                                (1 << 6)
#define PERI_CLK_SPI1                                (1 << 7)
#define PERI_CLK_SPI2                                (1 << 8)
#define PERI_CLK_SPI3                                (1 << 9)
#define PERI_CLK_PWMS                                (1 << 10)
#define PERI_CLK_SDIO                                (1 << 11)
#define PERI_CLK_EFUSE                               (1 << 12)
#define PERI_CLK_CEC                                 (1 << 13)

#define QSPI_CLK_MUX_POSI                            (16)
#define QSPI_CLK_MUX_MASK                            (0x3)
#define QSPI_CLK_MUX_DCO                             (0)
#define QSPI_CLK_MUX_26M                             (1)
#define QSPI_CLK_MUX_120M                            (2)

#define DCO_CLK_DIV_POSI                             (18)
#define DCO_CLK_DIV_MASK                             (0x3)
#define DCO_CLK_DIV_1                                (0)
#define DCO_CLK_DIV_2                                (1)
#define DCO_CLK_DIV_4                                (2)
#define DCO_CLK_DIV_8                                (3)

#define CLK26M_DIV_FACTOR_POSI                       (20)
#define CLK26M_DIV_FACTOR_MASK                       (0x3)
#define CLK26M_DIVISION_1                            (0x00)
#define CLK26M_DIVISION_2                            (0x01)
#define CLK26M_DIVISION_4                            (0x02)
#define CLK26M_DIVISION_8                            (0x03)

#define I2S_MCLK_DIV_POSI                             (24)
#define I2S_MCLK_DIV_MASK                             (0x7)
#define I2S_MCLK_DIV_1                                (0)
#define I2S_MCLK_DIV_2                                (1)
#define I2S_MCLK_DIV_4                                (2)
#define I2S_MCLK_DIV_8                                (3)
#define I2S_MCLK_DIV_16                               (4)
#define I2S_MCLK_DIV_32                               (5)

#define ICU_PWM_CLK_MUX                              (ICU_BASE + 1 * 4)
#define PWM_CLK_MUX_POSI                             (0)
#define PWM_CLK_MUX_MASK                             (0xF)
#define PWM_CLK_LPO                                  (1)
#define PWM_CLK_PCLK                                 (0)

#define SARADC_CLK_MUX_POSI                          (16)
#define SARADC_CLK_MUX_MASK                          (0x3)
#define SARADC_CLK_DCO                               (0)
#define SARADC_CLK_26M                               (1)
#define SARADC_CLK_AUDIOPLL                          (2)

#define ICU_PERI_CLK_PWD                             (ICU_BASE + 2 * 4)


#define ICU_FUNC_CLK_PWD                             (ICU_BASE + 3 * 4)

#define PWD_SDIO_DMA_CLK                             (1 << 6)
#define PWD_SECURITY_CLK                             (1 << 5)
#define PWD_QSPI_CLK                                 (1 << 4)
#define PWD_JEPG_CLK                                 (1 << 3)
#define PWD_USB2_CLK                                 (1 << 2)
#define PWD_USB1_CLK                                 (1 << 1)
#define PWD_ARM_WATCHDOG_CLK                         (1 << 0)

#define ICU_PERI_CLK_GATING                          (ICU_BASE + 4 * 4)

#define CLKGATE_DISABLE_LOGIC_ANALYZE_AHB            (1 << 26)
#define CLKGATE_DISABLE_GDMA_AHB                     (1 << 25)
#define CLKGATE_DISABLE_SDIO_DMA_AHB                 (1 << 24)
#define CLKGATE_DISABLE_SYS_CTRL_AHB                 (1 << 23)
#define CLKGATE_DISABLE_MEMORY_AHB                   (1 << 22)
#define CLKGATE_DISABLE_DCACHE_AHB                   (1 << 21)
#define CLKGATE_DISABLE_QSPI_AHB                     (1 << 20)
#define CLKGATE_DISABLE_FLASH_AHB                    (1 << 19)
#define CLKGATE_DISABLE_USB_AHB                      (1 << 18)
#define CLKGATE_DISABLE_MAC_AHB                      (1 << 17)
#define CLKGATE_DISABLE_MODEM_AHB                    (1 << 16)

#define CLKGATE_DISABLE_CEC_APB                      (1 << 11)
#define CLKGATE_DISABLE_SARADC_APB                   (1 << 10)
#define CLKGATE_DISABLE_PWM_APB                      (1 << 9)
#define CLKGATE_DISABLE_TIMER_APB                    (1 << 8)
#define CLKGATE_DISABLE_WATCHDOG_APB                 (1 << 7)
#define CLKGATE_DISABLE_GPIO_APB                     (1 << 6)
#define CLKGATE_DISABLE_SPI_APB                      (1 << 5)
#define CLKGATE_DISABLE_SDIO_APB                     (1 << 3)
#define CLKGATE_DISABLE_I2C_APB                      (1 << 2)
#define CLKGATE_DISABLE_UART_APB                     (1 << 1)
#define CLKGATE_DISABLE_ICU_APB                      (1 << 0)

#define ICU_JTAG_SELECT                              (ICU_BASE + 5 * 4)
#define JTAG_SEL_WR_ARM                              (0x7271F00F) /* JTAG_SEL_WR_WIFI actually */
#define JTAG_SEL_WR_BT                               (0x7271B00B)
#define JTAG_SEL_WR_TL4                              (0x7271D00D) /* JTAG_SEL_WR_DSP actually */
#define JTAG_SEL_RD_WIFI                             (0x00000000)
#define JTAG_SEL_RD_BT                               (0x00000001)
#define JTAG_SEL_RD_DSP                              (0x00000002)

#define ICU_INTERRUPT_ENABLE                         (ICU_BASE + 16 * 4)
#define FIQ_MAC_WAKEUP_EN_BIT                        (1 << 31) /* IRQ actually, compatible with legacy name */
#define FIQ_MAC_GENERAL_EN_BIT                       (1 << 30)
#define FIQ_MAC_PROT_TRIGGER_EN_BIT                  (1 << 29)
#define FIQ_MAC_TX_TRIGGER_EN_BIT                    (1 << 28)
#define FIQ_MAC_RX_TRIGGER_EN_BIT                    (1 << 27)
#define FIQ_MAC_TX_RX_MISC_EN_BIT                    (1 << 26)
#define FIQ_MAC_TX_RX_TIMER_EN_BIT                   (1 << 25)
#define FIQ_MODEM_EN_BIT                             (1 << 24)
#define FIQ_SECURITY_EN_BIT                          (1 << 23) /* IRQ actually, compatible with legacy name */
#define IRQ_MAILBOX2_EN_BIT                          (1 << 22)
#define IRQ_MAILBOX1_EN_BIT                          (1 << 21)
#define IRQ_GENERAL_DMA_EN_BIT                       (1 << 20)
#define FIQ_SDIO_DMA_EN_BIT                          (1 << 19) /* IRQ actually, compatible with legacy name */
#define IRQ_USB2_EN_BIT                              (1 << 18)
#define IRQ_QSPI_EN_BIT                              (1 << 17)
#define IRQ_SARADC_EN_BIT                            (1 << 16)
#define IRQ_PWM2_EN_BIT                              (1 << 15)
#define IRQ_PWM1_EN_BIT                              (1 << 14)
#define IRQ_TIMER_EN_BIT                             (1 << 13)
#define IRQ_IRDA_EN_BIT                              (1 << 12)
#define IRQ_GPIO_EN_BIT                              (1 << 11)
#define IRQ_SPI3_EN_BIT                              (1 << 10)
#define IRQ_SPI2_EN_BIT                              (1 << 9)
#define IRQ_SPI1_EN_BIT                              (1 << 8)
#define IRQ_USB1_EN_BIT                              (1 << 7)
#define IRQ_SDIO_EN_BIT                              (1 << 6)
#define IRQ_I2C2_EN_BIT                              (1 << 5)
#define IRQ_I2C1_EN_BIT                              (1 << 4)
#define IRQ_FM_I2C_EN_BIT                            (1 << 3)
#define IRQ_UART3_EN_BIT                             (1 << 2)
#define IRQ_UART2_EN_BIT                             (1 << 1)
#define IRQ_UART1_EN_BIT                             (1 << 0)

#define ICU_FIQ_ENABLE                               (ICU_BASE + 17 * 4)
#define FIQ_JEPG_EN_BIT                              (1 << 7)
#define FIQ_CEC_EN_BIT                               (1 << 6)
#define FIQ_TOUCH_EN_BIT                             (1 << 5)
#define FIQ_RTC_EN_BIT                               (1 << 4)
#define FIQ_DSP_WATCHDOG_EN_BIT                      (1 << 3)
#define FIQ_BT_WATCHDOG_EN_BIT                       (1 << 2)
#define FIQ_USB_PLUG_INOUT_EN_BIT                    (1 << 1)
#define FIQ_DPLL_UNLOCK_EN_BIT                       (1 << 0)

#define ICU_GLOBAL_INT_EN                            (ICU_BASE + 18 * 4)
#define GINTR_FIQ_EN                                 (1 << 1)
#define GINTR_IRQ_EN                                 (1 << 0)

#define ICU_INT_RAW_STATUS                           (ICU_BASE + 19 * 4)

#define ICU_FIQ_RAW_STATUS                           (ICU_BASE + 20 * 4)

#define ICU_INT_STATUS                               (ICU_BASE + 21 * 4)
#define FIQ_MAC_WAKEUP_STATUS_BIT                    (1 << 31) /* IRQ actually, compatible with legacy name */
#define FIQ_MAC_GENERAL_STATUS_BIT                   (1 << 30)
#define FIQ_MAC_PROT_TRIGGER_STATUS_BIT              (1 << 29)
#define FIQ_MAC_TX_TRIGGER_STATUS_BIT                (1 << 28)
#define FIQ_MAC_RX_TRIGGER_STATUS_BIT                (1 << 27)
#define FIQ_MAC_TX_RX_MISC_STATUS_BIT                (1 << 26)
#define FIQ_MAC_TX_RX_TIMER_STATUS_BIT               (1 << 25)
#define FIQ_MODEM_STATUS_BIT                         (1 << 24)
#define FIQ_SECURITY_STATUS_BIT                      (1 << 23) /* IRQ actually, compatible with legacy name */
#define IRQ_MAILBOX2_STATUS_BIT                      (1 << 22)
#define IRQ_MAILBOX1_STATUS_BIT                      (1 << 21)
#define IRQ_GENERAL_DMA_STATUS_BIT                   (1 << 20)
#define FIQ_SDIO_DMA_STATUS_BIT                      (1 << 19) /* IRQ actually, compatible with legacy name */
#define IRQ_USB2_STATUS_BIT                          (1 << 18)
#define IRQ_QSPI_STATUS_BIT                          (1 << 17)
#define IRQ_SARADC_STATUS_BIT                        (1 << 16)
#define IRQ_PWM2_STATUS_BIT                          (1 << 15)
#define IRQ_PWM1_STATUS_BIT                          (1 << 14)
#define IRQ_TIMER_STATUS_BIT                         (1 << 13)
#define IRQ_IRDA_STATUS_BIT                          (1 << 12)
#define IRQ_GPIO_STATUS_BIT                          (1 << 11)
#define IRQ_SPI3_STATUS_BIT                          (1 << 10)
#define IRQ_SPI2_STATUS_BIT                          (1 << 9)
#define IRQ_SPI1_STATUS_BIT                          (1 << 8)
#define IRQ_USB1_STATUS_BIT                          (1 << 7)
#define IRQ_SDIO_STATUS_BIT                          (1 << 6)
#define IRQ_I2C2_STATUS_BIT                          (1 << 5)
#define IRQ_I2C1_STATUS_BIT                          (1 << 4)
#define IRQ_FM_I2C_STATUS_BIT                        (1 << 3)
#define IRQ_UART3_STATUS_BIT                         (1 << 2)
#define IRQ_UART2_STATUS_BIT                         (1 << 1)
#define IRQ_UART1_STATUS_BIT                         (1 << 0)

#define ICU_FIQ_STATUS                               (ICU_BASE + 22 * 4)
#define CEC_ARM_WAKEUP_EN_BIT                        (1 << 6)
#define TOUCH_ARM_WAKEUP_EN_BIT                      (1 << 5)
#define RTC_ARM_WAKEUP_EN_BIT                        (1 << 4)
#define DSP_WATCHDOG_ARM_WAKEUP_EN_BIT               (1 << 3)
#define BT_WATCHDOG_ARM_WAKEUP_EN_BIT                (1 << 2)
#define USB_PLUG_INOUT_ARM_WAKEUP_EN_BIT             (1 << 1)
#define DPLL_UNLOCK_ARM_WAKEUP_EN_BIT                (1 << 0)

#define ICU_ARM_WAKEUP_EN                            (ICU_BASE + 23 * 4)
#define MAC_ARM_WAKEUP_EN_BIT                        (1 << 31)
#define MAC_GENERAL_ARM_WAKEUP_EN_BIT                (1 << 30)
#define MAC_PROT_TRIGGER_ARM_WAKEUP_EN_BIT           (1 << 29)
#define MAC_TX_TRIGGER_ARM_WAKEUP_EN_BIT             (1 << 28)
#define MAC_RX_TRIGGER_ARM_WAKEUP_EN_BIT             (1 << 27)
#define MAC_TX_RX_MISC_ARM_WAKEUP_EN_BIT             (1 << 26)
#define MAC_TX_RX_TIMER_ARM_WAKEUP_EN_BIT            (1 << 25)
#define MODEM_ARM_WAKEUP_EN_BIT                      (1 << 24)
#define SECURITY_ARM_WAKEUP_EN_BIT                   (1 << 23)
#define MAILBOX2_ARM_WAKEUP_EN_BIT                   (1 << 22)
#define MAILBOX1_ARM_WAKEUP_EN_BIT                   (1 << 21)
#define GENERAL_DMA_ARM_WAKEUP_EN_BIT                (1 << 20)
#define SDIO_DMA_ARM_WAKEUP_EN_BIT                   (1 << 19)
#define USB2_ARM_WAKEUP_EN_BIT                       (1 << 18)
#define QSPI_ARM_WAKEUP_EN_BIT                       (1 << 17)
#define SARADC_ARM_WAKEUP_EN_BIT                     (1 << 16)
#define PWM2_ARM_WAKEUP_EN_BIT                       (1 << 15)
#define PWM1_ARM_WAKEUP_EN_BIT                       (1 << 14)
#define TIMER_ARM_WAKEUP_EN_BIT                      (1 << 13)
#define IRDA_ARM_WAKEUP_EN_BIT                       (1 << 12)
#define GPIO_ARM_WAKEUP_EN_BIT                       (1 << 11)
#define SPI3_ARM_WAKEUP_EN_BIT                       (1 << 10)
#define SPI2_ARM_WAKEUP_EN_BIT                       (1 << 9)
#define SPI1_ARM_WAKEUP_EN_BIT                       (1 << 8)
#define USB1_ARM_WAKEUP_EN_BIT                       (1 << 7)
#define SDIO_ARM_WAKEUP_EN_BIT                       (1 << 6)
#define I2C2_ARM_WAKEUP_EN_BIT                       (1 << 5)
#define I2C1_ARM_WAKEUP_EN_BIT                       (1 << 4)
#define FM_I2C_ARM_WAKEUP_EN_BIT                     (1 << 3)
#define UART3_ARM_WAKEUP_EN_BIT                      (1 << 2)
#define UART2_ARM_WAKEUP_EN_BIT                      (1 << 1)
#define UART1_ARM_WAKEUP_EN_BIT                      (1 << 0)

#define ICU_ARM_WAKEUP2_EN                           (ICU_BASE + 24 * 4)
#define JEPG_ARM_WAKEUP_EN_BIT                       (1 << 7)
#define CEC_ARM_WAKEUP_EN_BIT                        (1 << 6)
#define TOUCH_ARM_WAKEUP_EN_BIT                      (1 << 5)
#define RTC_ARM_WAKEUP_EN_BIT                        (1 << 4)
#define DSP_WATCHDOG_ARM_WAKEUP_EN_BIT               (1 << 3)
#define BT_WATCHDOG_ARM_WAKEUP_EN_BIT                (1 << 2)
#define USB_PLUG_INOUT_ARM_WAKEUP_EN_BIT             (1 << 1)
#define DPLL_UNLOCK_ARM_WAKEUP_EN_BIT                (1 << 0)

#endif //_ICU_BK7271_H_
