#!/usr/bin/env python

import os
import sys
import json
import shutil
import argparse

out_json = {
    "magic": "RT-Thread",
    "version": "0.1",
    "count": 2,
    "section": [
        {
            "firmware": "bootloader_bk7231n_uart2_v1.0.9.bin",
            "version": "2M.1220",
            "partition": "bootloader",
            "start_addr": "0x00000000",
            "size": "65280"
        },
        {
            "firmware": "../../out/beken7231_bsp.bin",
            "version": "2M.1220",
            "partition": "app",
            "start_addr": "0x00011000",
            "size": "1156K"
        }
    ]
}

dsp_json = {
    "magic": "RT-Thread",
    "version": "0.1",
    "count": 2,
    "section": [
        {
            "firmware": "bootloader_bk7231n_uart2_v1.0.6.bin",
            "version": "2M.1220",
            "partition": "bootloader",
            "start_addr": "0x00000000",
            "size": "68K"
        },
        {
            "firmware": "../../out/beken7231_bsp.bin",
            "version": "2M.1220",
            "partition": "app",
            "start_addr": "0x00011000",
            "size": "1224K"
        },
        {
            "firmware": "dsp_code_data.bin",
            "version": "2M.1220",
            "partition": "dsp",
            "start_addr": "0x00143000",
            "size": "748K"
        },
        {
            "firmware": "BK7271_BT.bin",
            "version": "2M.1220",
            "partition": "bt",
            "start_addr": "0x001FE000",
            "size": "300K"
        }

    ]
}

chip_index = {
    1: 'bk7231',
    2: 'bk7231u',
    3: 'bk7251',
    4: 'bk7271',
    5: 'bk7231n',
    6: 'bk7236'
}

default_info = {
    'bk7231n': {'boot': 'bootloader_bk7231n_uart2_v1.0.10.bin', 'firmware': '../../out/beken7231_bsp.bin'},
    'bk7231u': {'boot': 'bootloader_bk7231u_uart2_v1.0.10.bin', 'firmware': '../../out/beken7231_bsp.bin'},
    'bk7231':  {'boot': 'bootloader_bk7231_uart2_v1.0.10.bin', 'firmware': '../../out/beken7231_bsp.bin'},
    'bk7251':  {'boot': 'bootloader_bk7251_uart2_v1.0.10.bin', 'firmware': '../../out/beken7231_bsp.bin'},
    'bk7271':  {'boot': 'bootloader_bk7271_uart2_v1.0.9.bin', 'firmware': '../../out/beken7231_bsp.bin', 'dsp': 'dsp_code_data.bin', 'bt': 'BK7271_BT.bin'},
    'bk7236':  {'boot': 'bootloader_bk7236_uart2_v1.0.10.bin', 'firmware': '../../out/beken7231_bsp.bin'},
}

# parse commandline arguments
def parse_args():
    description = '''Beken HID Downloader.'''
    parser = argparse.ArgumentParser(description=description)
    parser.add_argument('-c', '--chip',
                        default='bk7231u',
                        choices=default_info.keys(),
                        help="chip type, defaults to bk7231u")
    parser.add_argument('-i', '--index', type=int,
                        default=-1,
                        choices=chip_index.keys(),
                        help="chip index: 1: bk7231, 2: bk7231u, 3: bk7251, 4: bk7271, 5: bk7231n 6:bk7236")
    parser.add_argument('-b', '--boot',
                        help='specify boot file')
    parser.add_argument('-f', '--firmware',
                        help='specify firmware file')
    parser.add_argument('-d', '--dsp',
                        help='specify dsp file')
    parser.add_argument('-t', '--bt',
                        help='specify bt file')
    args = parser.parse_args()

    return args

args = parse_args()
chip = chip_index[args.index] if args.index>=0 else args.chip
bootloader_str = args.boot if args.boot else default_info[chip]['boot']
firmware_str = args.firmware if args.firmware else default_info[chip]['firmware']
if chip == 'bk7271':
    dsp_str = args.dsp if args.dsp else default_info[chip]['dsp']
    bt_str = args.bt if args.bt else default_info[chip]['bt']

out_path = "tmp.json"

if chip == 'bk7271':
    dsp_json["section"][0]["firmware"] = bootloader_str
    dsp_json["section"][1]["firmware"] = firmware_str
    dsp_json["section"][2]["firmware"] = dsp_str
    dsp_json["section"][3]["firmware"] = bt_str
    dsp_json = json.dumps(dsp_json, sort_keys=True, indent=4)
else:
    out_json["section"][0]["firmware"] = bootloader_str
    out_json["section"][1]["firmware"] = firmware_str
    out_json = json.dumps(out_json, sort_keys=True, indent=4)

#print(out_json)

with open(str(out_path), "w") as f:
    if chip == 'bk7271':
        f.write(dsp_json)
    else:
        f.write(out_json)

if sys.platform == 'win32':
    os.system("beken_packager {}".format(out_path))
elif sys.platform == 'darwin':
    os.system("./beken_packager.darwin {}".format(out_path))
else:
    os.system("./beken_packager {}".format(out_path))
shutil.move("all_2M.1220.bin", "../../out/all_2M.1220.bin")
shutil.move("beken7231_bsp_uart_2M.1220.bin", "../../out/beken7231_bsp_uart_2M.1220.bin")
shutil.copy(bootloader_str, "../../out/" + bootloader_str)
os.remove(out_path)
